CXX = g++
CXXFLAGS = -std=c++0x
SRCS = menu.cpp main.cpp grid.cpp ant.cpp
HEADERS = menu.hpp grid.hpp ant.hpp

assignment1: ${SRCS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SRCS} -o assignment1

clean:
	$(RM) assignment1